version: '3.8'

services:
  master:
    image: mysql:8.0
    container_name: mysql-master
    restart: always
    command:
      [
        "--default-authentication-plugin=mysql_native_password",
        "--server-id=1",
        "--log-bin=mysql-bin",
        "--binlog-format=ROW"
      ]
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nickopolis
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - master_data:/var/lib/mysql
      - ./init-master.sql:/docker-entrypoint-initdb.d/init-master.sql:ro

  slave1:
    image: mysql:8.0
    container_name: mysql-slave1
    restart: always
    command:
      [
        "--default-authentication-plugin=mysql_native_password",
        "--server-id=2",
        "--log-bin=mysql-bin",
        "--relay-log=mysql-relay-bin"
      ]
    depends_on:
      - master
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - slave1_data:/var/lib/mysql

  slave2:
    image: mysql:8.0
    container_name: mysql-slave2
    restart: always
    command:
      [
        "--default-authentication-plugin=mysql_native_password",
        "--server-id=3",
        "--log-bin=mysql-bin",
        "--relay-log=mysql-relay-bin"
      ]
    depends_on:
      - master
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - slave2_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"

  go:
    build: .
    ports:
      - "81:80"
    depends_on:
      master:
        condition: service_healthy
      slave1:
        condition: service_healthy
      slave2:
        condition: service_healthy
    environment:
      - DB_HOST=mysql-master
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=nickopolis

volumes:
  master_data:
  slave1_data:
  slave2_data: